services:
  - type: web
    name: moodbite-backend
    env: python-3.10
    # runtime: python-3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    
